# Generated by Django 4.2.30 on 2026-09-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='icon',
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_topics', to='subjects.subject'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='subjects.subject')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.module'),
        ),
        migrations.CreateModel(
            name='ModuleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='learning_materials/pdfs/')),
                ('file_path', models.CharField(blank=True, default='', help_text='Storage path or URI reference', max_length=500)),
                ('document_type', models.CharField(choices=[('notes', 'Notes'), ('reference', 'Reference'), ('syllabus', 'Syllabus'), ('cheatsheet', 'Cheat Sheet')], default='notes', max_length=20)),
                ('indexing_status', models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='subjects.module')),
            ],
            options={
                'ordering': ['module', 'id'],
                'indexes': [models.Index(fields=['module', 'indexing_status'], name='subjects_mo_module__e03fa0_idx')],
            },
        ),
    ]
