# Generated by Django 4.2.30 on 2026-09-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_topic_unique_together_remove_subject_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.module'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('module', 'name')},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
    ]
