# Generated by Django 4.2.30 on 2026-09-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_topic_module_alter_topic_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.module'),
        ),
    ]
