# Generated by Django 4.2.30 on 2026-09-13 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='exams.test')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='subjects.topic')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=255)),
                ('correct_option', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='progress.testresult')),
            ],
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_difficulty', models.CharField(default='easy', max_length=10)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('best_score', models.FloatField(default=0.0)),
                ('last_score', models.FloatField(default=0.0)),
                ('attempt_count', models.IntegerField(default=0)),
                ('reinforcement_count', models.IntegerField(default=0)),
                ('trend', models.CharField(default='stable', max_length=20)),
                ('last_decision', models.CharField(default='reinforce', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progresses', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='subjects.topic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
