# Generated by Django 4.2.30 on 2026-09-13 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_mastery', models.FloatField(default=0.0)),
                ('topics_completed', models.IntegerField(default=0)),
                ('total_topics', models.IntegerField(default=0)),
                ('total_tests_taken', models.IntegerField(default=0)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_progresses', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='subjects.subject')),
            ],
            options={
                'verbose_name_plural': 'Subject Progresses',
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_tag', models.CharField(max_length=100)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_masteries', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_masteries', to='subjects.topic')),
            ],
            options={
                'verbose_name_plural': 'Concept Masteries',
                'unique_together': {('student', 'topic', 'concept_tag')},
            },
        ),
    ]
