# Generated by Django 4.2.30 on 2026-09-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty'], name='exams_quest_topic_i_c90d7a_idx'),
        ),
    ]
