# Generated by Django 4.2.30 on 2026-09-13 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0002_alter_topic_unique_together_remove_subject_icon_and_more'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('max_students', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mentorrequest',
            name='assigned_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mentorships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorrequest',
            name='concept_tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mentorrequest',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_requests', to='subjects.module'),
        ),
        migrations.AddField(
            model_name='mentorrequest',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='mentorrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('assigned', 'Assigned'), ('in_review', 'In Review'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorrequest',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_requests', to='subjects.topic'),
        ),
        migrations.AddIndex(
            model_name='mentorrequest',
            index=models.Index(fields=['subject', 'status'], name='mentor_ment_subject_cbd62f_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorrequest',
            index=models.Index(fields=['student', 'subject'], name='mentor_ment_student_479a9f_idx'),
        ),
        migrations.AddField(
            model_name='subjectmentor',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mentorships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectmentor',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='subjects.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectmentor',
            unique_together={('mentor', 'subject')},
        ),
    ]
