# Generated by Django 4.2.30 on 2026-09-13 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('reinforce', 'Reinforce'), ('advance', 'Advance'), ('mentor', 'Mentor')], max_length=20)),
                ('next_difficulty', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('weak_areas', models.JSONField(default=list)),
                ('recommended_action', models.TextField()),
                ('confidence', models.FloatField(default=0.9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_decisions', to=settings.AUTH_USER_MODEL)),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_decisions', to='progress.testresult')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_decisions', to='subjects.topic')),
            ],
        ),
    ]
